kind: Service
apiVersion: v1
metadata:
  name: mysql-slaver
  namespace: cdmi-default
  labels:
    app: mysql-slaver
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: v1
    version: v1
  annotations:
    kubesphere.io/creator: wuwei
    kubesphere.io/serviceType: statefulservice
    servicemesh.kubesphere.io/enabled: ‘false’
spec:
  type: NodePort
  ports:
    - port: 3307
      protocol: TCP
      targetPort: 3307
      nodePort: 31307
  selector:
    app: mysql-slaver
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: v1