kind: Service
apiVersion: v1
metadata:
  name: www-nginx
  namespace: cdmi-default
  labels:
    app: www-nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: v1
    version: v1
  annotations:
    kubesphere.io/creator: wuwei
    kubesphere.io/serviceType: statefulservice
    servicemesh.kubesphere.io/enabled: ‘false’
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31080
  selector:
    app: www-nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: v1